gm_custom_attrs:
  - level
  - resume
  - academic_career_es
  - research_interests_es
  - research_photo
  - links
  - publications
  - activities_or_topics_es

gm_default_attrs:
  - firstname
  - lastname
  - photo_file_name
  - email
  - phone_numbers
  - catalogs_member_type
  - group
  - current_workplace
  - current_position_es
  - current_position_en
  - links_link
  - links_name_es
  - links_name_en
  - publications_title
  - publications_catalogs_pub_type
  - publications_pub_date
  - publications_link
  - catalogs_level
