gm_custom_attrs:
  - level
  - resume
  - academic_career:
    - academic_career_es
    - academic_career_en
  - research_interests:
    - research_interests_es
    - research_interests_en
  - activities_or_topics:
    - activities_or_topics_es
    - activities_or_topics_en
  - research_photo:
    - research_photo
    - research_photo_descr_es
    - research_photo_descr_en
  - links
  - publications

gm_default_attrs:
  - firstname
  - lastname
  - photo_file_name
  - email
  - phone_numbers
  - catalogs_member_type
  - group
  - current_workplace
  - current_position_es
  - current_position_en
  - links_link
  - links_name_es
  - links_name_en
  - publications_title
  - publications_catalogs_pub_type
  - publications_pub_date
  - publications_link
  - catalogs_level
